pipeline {
    agent any

    parameters {
        text(name: 'DEV_PROPERTY_OVERRIDES', description: 'Which properties should we override?')
        text(name: 'TST_PROPERTY_OVERRIDES', description: 'Which properties should we override?')
        text(name: 'PRD_PROPERTY_OVERRIDES', description: 'Which properties should we override?')
        text(name: 'VERSION_TO_DEPLOY', description: 'Which previously deployed version should we deploy?')
    }

    environment {
        // Jenkins will set anypoint_credentials_usr and anypoint_credentials_psw respectively
        anypoint_credentials = credentials('anypoint-creds')
        anypoint_org_id = 'f2ea2cb4-c600-4bb5-88e8-e952ff5591ee'
        version = "${params.VERSION_TO_DEPLOY ?: '1.0.' + env.BUILD_NUMBER}"
    }

    stages {
        stage('Deploy') {
            environment {
                anypoint_environment = 'DEV'
            }

            steps {
                echo "the version is ${env.version}"
                muleDeployOnPrem zipFilePath: '/mule_project/src/test/resources/mule_project/target/tester-1.0.0.zip',
                                 appName:  'the-app-2',
                                 targetServerOrClusterName: 'bradytest2'
            }
        }
    }
}
